" Generated by vim-plug
" Sat 18 Jun 18:45:01 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = '79b356d00586ab9e6ffd1fbf732bf4f076c95d20'
silent! let g:plugs['cmp-buffer'].commit = 'd66c4c2d376e5be99db68d2362cd94d250987525'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'e6b5feb2e6560b61f31c756fb9231a0d7b10c73d'
silent! let g:plugs['cmp-path'].commit = '466b6b8270f7ba89abd59f402c73f63c7331ff6e'
silent! let g:plugs['conjure'].commit = '842c81892648de759e639ad2d395757b98be06d5'
silent! let g:plugs['gitsigns.nvim'].commit = '0beb1941641bd7d5d7072d3612ee47c0eb80b63d'
silent! let g:plugs['janet.vim'].commit = 'cf2bea62a7f4e1080a382b930c069cdeece17a24'
silent! let g:plugs['kanagawa.nvim'].commit = '50e7b43552072696d26757aff5f6307e2ab5e3ea'
silent! let g:plugs['lualine.nvim'].commit = '619ededcff79e33a7e0ea677881dd07957449f9d'
silent! let g:plugs['nvim-cmp'].commit = 'f81bfee10909e39c82ccd230f6f997438b16092e'
silent! let g:plugs['nvim-lspconfig'].commit = '2f37b2ca07a3f89e7994b3b7f54c997e2cb3400a'
silent! let g:plugs['nvim-tree.lua'].commit = '9049f364cc3ceaff07ab130e1d35aec9e4124563'
silent! let g:plugs['nvim-treesitter'].commit = '9069849533c28fe963cb0c649d94de828b9f9666'
silent! let g:plugs['nvim-web-devicons'].commit = 'bdd43421437f2ef037e0dafeaaaa62b31d35ef2f'
silent! let g:plugs['plenary.nvim'].commit = '9069d14a120cadb4f6825f76821533f2babcab92'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '281b07a5cba2dc255e2a35d3fa6e49af0c8cb37f'
silent! let g:plugs['telescope.nvim'].commit = '4681dcdffe20e1f23b6b9ccf28836537ed166c47'
silent! let g:plugs['vim-dispatch'].commit = '00e77d90452e3c710014b26dc61ea919bc895e92'
silent! let g:plugs['vim-dispatch-neovim'].commit = 'c8c4e21a95c25032a041002f9bf6e45a75a73021'
silent! let g:plugs['vim-jack-in'].commit = '5467e00e26f15680b0a7998f8aa20d5a7dd44cd5'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['which-key.nvim'].commit = 'bd4411a2ed4dd8bb69c125e339d837028a6eea71'

PlugUpdate!

