" Generated by vim-plug
" Fri 15 Jul 13:35:13 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = '7c49fb2ac01a9f03410100c8e78f647bbea857e8'
silent! let g:plugs['LuaSnip'].commit = '8f71a7c9d6155413f85df4a2350f59d0abd46dfc'
silent! let g:plugs['cmp-buffer'].commit = '62fc67a2b0205136bc3e312664624ba2ab4a9323'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-path'].commit = '981baf9525257ac3269e1b6701e376d6fbff6921'
silent! let g:plugs['cmp_luasnip'].commit = 'a9de941bcbda508d0a45d28ae366bb3f08db2e36'
silent! let g:plugs['conjure'].commit = '2e7f449d06753f2996e186954e96afc60edd5862'
silent! let g:plugs['gitsigns.nvim'].commit = 'bb6c3bf6f584e73945a0913bb3adf77b60d6f6a2'
silent! let g:plugs['janet.vim'].commit = 'eb520a727e775a917c078d9fa6777572171a7e94'
silent! let g:plugs['kanagawa.nvim'].commit = 'a423ff33e9f9182cf6ee346ae19df2583ab37f55'
silent! let g:plugs['lualine.nvim'].commit = '655411fb7aa3cf4d46094132d684d815453f5043'
silent! let g:plugs['nvim-cmp'].commit = '9897465a7663997b7b42372164ffc3635321a2fe'
silent! let g:plugs['nvim-lspconfig'].commit = '0da8c129dc27e70770c3247c44988bbf0af6b1af'
silent! let g:plugs['nvim-tree.lua'].commit = '449b5bd0cbe08192ded83b2bce8cbec4764da63d'
silent! let g:plugs['nvim-treesitter'].commit = '3bd228781bf4a927c5ceaf7a4687fed9f96d12b5'
silent! let g:plugs['nvim-web-devicons'].commit = '2d02a56189e2bde11edd4712fea16f08a6656944'
silent! let g:plugs['plenary.nvim'].commit = '986ad71ae930c7d96e812734540511b4ca838aa2'
silent! let g:plugs['rust-tools.nvim'].commit = '11dcd674781ba68a951ab4c7b740553cae8fe671'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '6a33ecefa9b3d9ade654f9a7a6396a00c3758ca6'
silent! let g:plugs['telescope.nvim'].commit = 'b79cd6c88b3d96b0f49cb7d240807cd59b610cd8'
silent! let g:plugs['vim-dispatch'].commit = '00e77d90452e3c710014b26dc61ea919bc895e92'
silent! let g:plugs['vim-dispatch-neovim'].commit = 'c8c4e21a95c25032a041002f9bf6e45a75a73021'
silent! let g:plugs['vim-jack-in'].commit = '5467e00e26f15680b0a7998f8aa20d5a7dd44cd5'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['which-key.nvim'].commit = 'bd4411a2ed4dd8bb69c125e339d837028a6eea71'

PlugUpdate!

