" Generated by vim-plug
" Sat 13 Aug 19:18:22 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = '4818a4c2ecf64ace6358b81073ad5d76f657953d'
silent! let g:plugs['LuaSnip'].commit = 'b8fa22fc12df7a8c48f5c18156874d40f584265c'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-path'].commit = '447c87cdd6e6d6a1d2488b1d43108bfa217f56e1'
silent! let g:plugs['cmp_luasnip'].commit = 'a9de941bcbda508d0a45d28ae366bb3f08db2e36'
silent! let g:plugs['conjure'].commit = '08236a13164a948fe403f34fe1f593ead0a3c6fe'
silent! let g:plugs['gitsigns.nvim'].commit = '29468d89e71a0cd04aeb750fcfe75c3163347adf'
silent! let g:plugs['janet.vim'].commit = 'eb520a727e775a917c078d9fa6777572171a7e94'
silent! let g:plugs['kanagawa.nvim'].commit = '6fe60d5f9d1cae16084f8051c02bf2613187c4f6'
silent! let g:plugs['lualine.nvim'].commit = 'c0510ddec86070dbcacbd291736de27aabbf3bfe'
silent! let g:plugs['nvim-cmp'].commit = '706371f1300e7c0acb98b346f80dad2dd9b5f679'
silent! let g:plugs['nvim-lspconfig'].commit = 'da7461b596d70fa47b50bf3a7acfaef94c47727d'
silent! let g:plugs['nvim-tree.lua'].commit = '261a5c380c000e23c4a23dcd55b984c856cdb113'
silent! let g:plugs['nvim-treesitter'].commit = '48d88ddbff301d69703f0942c75603d545670782'
silent! let g:plugs['nvim-web-devicons'].commit = '2d02a56189e2bde11edd4712fea16f08a6656944'
silent! let g:plugs['plenary.nvim'].commit = '31807eef4ed574854b8a53ae40ea3292033a78ea'
silent! let g:plugs['rust-tools.nvim'].commit = 'af266e4ded06d5ec7b68490eab165a837c77567c'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '6791f74e9f08a9412c43dcba805ecf2f8888bdde'
silent! let g:plugs['telescope.nvim'].commit = 'd793de0f12d874c463e81edabee741b802c1a37a'
silent! let g:plugs['vim-dispatch'].commit = '00e77d90452e3c710014b26dc61ea919bc895e92'
silent! let g:plugs['vim-dispatch-neovim'].commit = 'c8c4e21a95c25032a041002f9bf6e45a75a73021'
silent! let g:plugs['vim-jack-in'].commit = '5467e00e26f15680b0a7998f8aa20d5a7dd44cd5'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['which-key.nvim'].commit = 'bd4411a2ed4dd8bb69c125e339d837028a6eea71'

PlugUpdate!

