" Generated by vim-plug
" Wed  5 Apr 13:10:06 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Comment.nvim'].commit = '8d3aa5c22c2d45e788c7a5fe13ad77368b783c20'
silent! let g:plugs['LuaSnip'].commit = 'bc8ec05022743d3f08bda7a76c6bb5e9a9024581'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '0e6b2ed705ddcff9738ec4ea838141654f12eeef'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp_luasnip'].commit = '18095520391186d634a0045dacaa346291096566'
silent! let g:plugs['conjure'].commit = '51936288d182a677fcb808e660081ad7e9ecd4ec'
silent! let g:plugs['elm-vim'].commit = '4b71facd77297cb33bbb3b14894676cff0a9bd1d'
silent! let g:plugs['gitsigns.nvim'].commit = '372d5cb485f2062ac74abc5b33054abac21d8b58'
silent! let g:plugs['janet.vim'].commit = '61eca1138bd149a86edbde39dc20a3130f0d9b39'
silent! let g:plugs['kanagawa.nvim'].commit = '5c4037432f0ae2d0b75d3a7b7cfa3022d7054e4d'
silent! let g:plugs['lualine.nvim'].commit = 'c28a7427c3fb29322db136f0564ec58807b26747'
silent! let g:plugs['nvim-cmp'].commit = '777450fd0ae289463a14481673e26246b5e38bf2'
silent! let g:plugs['nvim-dap'].commit = '1dd02e82c77d558e30ba831db4c2e7ed534e874f'
silent! let g:plugs['nvim-dap-go'].commit = 'b4ded7de579b4e2a85c203388233b54bf1028816'
silent! let g:plugs['nvim-dap-ui'].commit = '56a2df0e96bfa64ebd6967e7cad877a1530633d5'
silent! let g:plugs['nvim-lspconfig'].commit = '7179a46c2345050783d14397e672e7b152a7af4f'
silent! let g:plugs['nvim-tree.lua'].commit = 'd1410cb0896a3aad5d84ddc54284774a627c6d63'
silent! let g:plugs['nvim-treesitter'].commit = '411e771d511442ab81670701f5c830f6c74aadd7'
silent! let g:plugs['nvim-web-devicons'].commit = '0568104bf8d0c3ab16395433fcc5c1638efc25d4'
silent! let g:plugs['plenary.nvim'].commit = '253d34830709d690f013daf2853a9d21ad7accab'
silent! let g:plugs['roc.vim'].commit = 'a4b2edc029b349f05221249a6ab922d2787d2962'
silent! let g:plugs['rust-tools.nvim'].commit = '71d2cf67b5ed120a0e31b2c8adb210dd2834242f'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = '580b6c48651cabb63455e97d7e131ed557b8c7e2'
silent! let g:plugs['telescope.nvim'].commit = '942fe5faef47b21241e970551eba407bc10d9547'
silent! let g:plugs['vim-dispatch'].commit = '6cc2691576f97d43f8751664d1a1a908b99927e5'
silent! let g:plugs['vim-dispatch-neovim'].commit = 'c8c4e21a95c25032a041002f9bf6e45a75a73021'
silent! let g:plugs['vim-jack-in'].commit = '8ca306a9484d6d184de8921a9cab03c63ee9aa79'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = 'cc5923e357373ea6ef0c13eae82f44e6b9b1d374'
silent! let g:plugs['which-key.nvim'].commit = '4b73390eec680b4c061ea175eb32c0ff3412271d'

PlugUpdate!

