theme = "kanagawa"

[editor]
true-color = true
bufferline = "multiple"
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal.space]
q = ":quit"
W = ":write"
B = ":buffer-close"
